### ISSUE TITLE
Assigning GPS locations to EM-APEX ctd and vel data based on interpolation

### ISSUE THREAD

**Issue by emiliom** [emiliom/squid-dinosip#6]
@ElizabethP712 I'm making progress on this. I have the technique figured out with toy data. Now I need to test it with the actual data. I'll post it here by mid-late afternoon once I've tested it.

**Comment by emiliom** [comment]
Here you go: [squid-vel-interpolate-gps.ipynb](https://github.com/emiliom/squid-dinosip/blob/main/squid-vel-interpolate-gps.ipynb)

**Comment by ElizabethP712** [comment]
Thank you! I haven't had a chance to apply this yet, but once it works I will resolve this issue.

**Comment by ElizabethP712** [comment]
Hey Emilio!

It is probably a good thing you had me run through this notebook today, as I ran into an error with the interpolation step and slinear method. Please see the new file I just uploaded titled [Errorsquid-vel-interpolate-gps.ipynb](https://github.com/emiliom/squid-dinosip/blob/fa8f95b521dfb18989557af22932f21c38292934/Errorsquid-vel-interpolate-gps.ipynb).

**Comment by emiliom** [comment]
That's very strange! I'll try to take a look later tonight.

**Comment by emiliom** [comment]
I reran the notebook, and it again worked fine. But then I realized that I didn't use the AOS conda environment; I think I was in a hurry and didn't want to install pyarrow on that environment, so I used a different one. So, it's possible there are some subtle differences in a dependency.

At this point in time, it's more important for you to have access to the merged-interpolated EM-APEX data than to be able to run my notebook. So, I've uploaded the merged file to the Google Drive folder where the other EM-APEX data files are. It's called `vel_gps_interpolated_smile2017only.parquet`, and it's only about 17 MB. **This file is already filtered so it contains only SMILE data, and only data from 2017.**

FYI I've updated the notebook in the repo.

**Comment by ElizabethP712** [comment]
Okay, I think today and tomorrow I will focus on the velocity dataset you uploaded to do some last minute comparisons. My poster is mostly done by now I just have these velocity comparisons to do, I have a few things I am going to add (text wise) for some of my other graphs, and I want to decide on what the highlight of my project is, but other than that I should have a copy of the poster (and text, as it will be easier to read that way) uploaded to a new issue for you to review tomorrow, especially considering I will not be able to work on the poster again until after 4:30pm tomorrow since the interns are going hiking.
